services:
  - type: web
    name: darkroom-gallery
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        sync: false
        value: mongodb+srv://allanwasega:QTcNJKGTiIct3JdP@moringaip1.qo4izwt.mongodb.net/darkroom?retryWrites=true&w=majority
    healthCheckPath: /
    autoDeploy: true
    branch: ip1 